server:
  port: 8081
spring:
  profiles:
    active: prod
---


server:
  port: 8080
spring:
  profiles: prod
---
server:
  port: 8083
spring:
  profiles: dev
#
#person:
#  lastName: zhangsan
#  age: 18
#  boss: false
#  birth: 2017/01/01
#  maps: {k1:v1,k2:12}
#  lists:
#    - lisi
#    - zhaoliu
#  dog:
#    name: 小狗
#    age: 2